--1.迁移前-清除备份表
drop table ENT_INFO_MIG1_20181205;
drop table CUSTOMER_RELATIVE_MIG1_20181205;
drop table CUSTOMER_BELONG_MIG1_20181205;
drop table IND_INFO_MIG1_20181205;
drop table CUSTOMER_ADDRESS_MIG1_20181205;
drop table CUSTOMER_TEL_MIG1_20181205;
drop table CUSTOMER_CERT_MIG1_20181205;
drop table BUSINESS_APPROVE_MIG1_20181205;
drop table BUSINESS_CONTRACT_MIG1_20181205;
drop table BUSINESS_DUEBILL_MIG1_20181205;
drop table GUARANTY_CONTRACT_MIG1_20181205;
drop table GUARANTY_INFO_MIG1_20181205;
drop table GUARANTY_RELATIVE_MIG1_20181205;
drop table CL_INFO_MIG1_20181205;
drop table CL_DIVIDE_MIG1_20181205;
drop table CL_OCCUPY_MIG1_20181205;
drop table BUSINESS_WASTEBOOK_MIG1_20181205;
drop table GROUP_INFO_MIG1_20181205;
drop table GROUP_MEMBER_RELATIVE_MIG1_20181205;
drop table CONTRACT_RELATIVE_MIG1_20181205;
drop table CMS_INSURANCE_INFO_MIG1_20181205;
drop table CUSTOMER_INFO_MIG1_20181205;
drop table CL_CREDIT_SAME_MIG1_20181205;
drop table APPLY_BATCHRELATIVE_MIG1_20181205;
drop table CLASSIFY_RECORD_MIG1_20181205;
drop table MARGIN_INFO_MIG1_20181205;
drop table BUSINESS_IMAGE_RELATIVE_MIG1_20181205;
drop table BUSINESS_APPLY_MIG1_20181205;
drop table FLOW_OBJECT_MIG1_20181205;
drop table FLOW_TASK_MIG1_20181205;
drop table APPLY_RELATIVE_MIG1_20181205;
drop table APPROVE_RELATIVE_MIG1_20181205;
drop table BUSINESS_PUTOUT_MIG1_20181205;
drop table BILL_INFO_MIG1_20181205;

--创建备份表
create table ENT_INFO_MIG1_20181205 as select * from ENT_INFO;
create table CUSTOMER_RELATIVE_MIG1_20181205 as select * from CUSTOMER_RELATIVE;
create table CUSTOMER_BELONG_MIG1_20181205 as select * from CUSTOMER_BELONG;
create table IND_INFO_MIG1_20181205 as select * from IND_INFO;
create table CUSTOMER_ADDRESS_MIG1_20181205 as select * from CUSTOMER_ADDRESS;
create table CUSTOMER_TEL_MIG1_20181205 as select * from CUSTOMER_TEL;
create table CUSTOMER_CERT_MIG1_20181205 as select * from CUSTOMER_CERT;
create table BUSINESS_APPROVE_MIG1_20181205 as select * from BUSINESS_APPROVE;
create table BUSINESS_CONTRACT_MIG1_20181205 as select * from BUSINESS_CONTRACT;
create table BUSINESS_DUEBILL_MIG1_20181205 as select * from BUSINESS_DUEBILL;
create table GUARANTY_CONTRACT_MIG1_20181205 as select * from GUARANTY_CONTRACT;
create table GUARANTY_INFO_MIG1_20181205 as select * from GUARANTY_INFO;
create table GUARANTY_RELATIVE_MIG1_20181205 as select * from GUARANTY_RELATIVE;
create table CL_INFO_MIG1_20181205 as select * from CL_INFO;
create table CL_DIVIDE_MIG1_20181205 as select * from CL_DIVIDE;
create table CL_OCCUPY_MIG1_20181205 as select * from CL_OCCUPY;
create table BUSINESS_WASTEBOOK_MIG1_20181205 as select * from BUSINESS_WASTEBOOK;
create table GROUP_INFO_MIG1_20181205 as select * from GROUP_INFO;
create table GROUP_MEMBER_RELATIVE_MIG1_20181205 as select * from GROUP_MEMBER_RELATIVE;
create table CONTRACT_RELATIVE_MIG1_20181205 as select * from CONTRACT_RELATIVE;
create table CMS_INSURANCE_INFO_MIG1_20181205 as select * from CMS_INSURANCE_INFO;
create table CUSTOMER_INFO_MIG1_20181205 as select * from CUSTOMER_INFO;
create table CL_CREDIT_SAME_MIG1_20181205 as select * from CL_CREDIT_SAME;
create table APPLY_BATCHRELATIVE_MIG1_20181205 as select * from APPLY_BATCHRELATIVE;
create table CLASSIFY_RECORD_MIG1_20181205 as select * from CLASSIFY_RECORD;
create table MARGIN_INFO_MIG1_20181205 as select * from MARGIN_INFO;
create table BUSINESS_IMAGE_RELATIVE_MIG1_20181205 as select * from BUSINESS_IMAGE_RELATIVE;
create table BUSINESS_APPLY_MIG1_20181205 as select * from BUSINESS_APPLY;
create table FLOW_OBJECT_MIG1_20181205 as select * from FLOW_OBJECT;
create table FLOW_TASK_MIG1_20181205 as select * from FLOW_TASK;
create table APPLY_RELATIVE_MIG1_20181205 as select * from APPLY_RELATIVE;
create table APPROVE_RELATIVE_MIG1_20181205 as select * from APPROVE_RELATIVE;
create table BUSINESS_PUTOUT_MIG1_20181205 as select * from BUSINESS_PUTOUT;
create table BILL_INFO_MIG1_20181205 as select * from BILL_INFO;

--2.删除中间表
drop table ENT_INFO_MIG;
drop table CUSTOMER_RELATIVE_MIG;
drop table CUSTOMER_BELONG_MIG;
drop table IND_INFO_MIG;
drop table CUSTOMER_ADDRESS_MIG;
drop table CUSTOMER_TEL_MIG;
drop table CUSTOMER_CERT_MIG;
drop table BUSINESS_APPROVE_MIG;
drop table BUSINESS_CONTRACT_MIG;
drop table BUSINESS_DUEBILL_MIG;
drop table GUARANTY_CONTRACT_MIG;
drop table GUARANTY_INFO_MIG;
drop table GUARANTY_RELATIVE_MIG;
drop table CL_INFO_MIG;
drop table CL_DIVIDE_MIG;
drop table CL_OCCUPY_MIG;
drop table BUSINESS_WASTEBOOK_MIG;
drop table GROUP_INFO_MIG;
drop table GROUP_MEMBER_RELATIVE_MIG;
drop table CONTRACT_RELATIVE_MIG;
drop table CMS_INSURANCE_INFO_MIG;
drop table CUSTOMER_INFO_MIG;
drop table CL_CREDIT_SAME_MIG;
drop table APPLY_BATCHRELATIVE_MIG;
drop table CLASSIFY_RECORD_MIG;
drop table MARGIN_INFO_MIG;
drop table BUSINESS_IMAGE_RELATIVE_MIG;
drop table BUSINESS_APPLY_MIG;
drop table FLOW_OBJECT_MIG;
drop table FLOW_TASK_MIG;
drop table APPLY_RELATIVE_MIG;
drop table APPROVE_RELATIVE_MIG;
drop table BUSINESS_PUTOUT_MIG;
drop table BILL_INFO_MIG;

--3.新建临时表
create table ENT_INFO_MIG as select * from ENT_INFO;
create table CUSTOMER_RELATIVE_MIG as select * from CUSTOMER_RELATIVE;
create table CUSTOMER_BELONG_MIG as select * from CUSTOMER_BELONG;
create table IND_INFO_MIG as select * from IND_INFO;
create table CUSTOMER_ADDRESS_MIG as select * from CUSTOMER_ADDRESS;
create table CUSTOMER_TEL_MIG as select * from CUSTOMER_TEL;
create table CUSTOMER_CERT_MIG as select * from CUSTOMER_CERT;
create table BUSINESS_APPROVE_MIG as select * from BUSINESS_APPROVE;
create table BUSINESS_CONTRACT_MIG as select * from BUSINESS_CONTRACT;
create table BUSINESS_DUEBILL_MIG as select * from BUSINESS_DUEBILL;
create table GUARANTY_CONTRACT_MIG as select * from GUARANTY_CONTRACT;
create table GUARANTY_INFO_MIG as select * from GUARANTY_INFO;
create table GUARANTY_RELATIVE_MIG as select * from GUARANTY_RELATIVE;
create table CL_INFO_MIG as select * from CL_INFO;
create table CL_DIVIDE_MIG as select * from CL_DIVIDE;
create table CL_OCCUPY_MIG as select * from CL_OCCUPY;
create table BUSINESS_WASTEBOOK_MIG as select * from BUSINESS_WASTEBOOK;
create table GROUP_INFO_MIG as select * from GROUP_INFO;
create table GROUP_MEMBER_RELATIVE_MIG as select * from GROUP_MEMBER_RELATIVE;
create table CONTRACT_RELATIVE_MIG as select * from CONTRACT_RELATIVE;
create table CMS_INSURANCE_INFO_MIG as select * from CMS_INSURANCE_INFO;
create table CUSTOMER_INFO_MIG as select * from CUSTOMER_INFO;
create table CL_CREDIT_SAME_MIG as select * from CL_CREDIT_SAME;
create table APPLY_BATCHRELATIVE_MIG as select * from APPLY_BATCHRELATIVE;
create table CLASSIFY_RECORD_MIG as select * from CLASSIFY_RECORD;
create table MARGIN_INFO_MIG as select * from MARGIN_INFO;
create table BUSINESS_IMAGE_RELATIVE_MIG as select * from BUSINESS_IMAGE_RELATIVE;
create table BUSINESS_APPLY_MIG as select * from BUSINESS_APPLY;
create table FLOW_OBJECT_MIG as select * from FLOW_OBJECT;
create table FLOW_TASK_MIG as select * from FLOW_TASK;
create table APPLY_RELATIVE_MIG as select * from APPLY_RELATIVE;
create table APPROVE_RELATIVE_MIG as select * from APPROVE_RELATIVE;
create table BUSINESS_PUTOUT_MIG as select * from BUSINESS_PUTOUT;
create table BILL_INFO_MIG as select * from BILL_INFO;

--4.清除临时表数据
truncate table ENT_INFO_MIG;
truncate table CUSTOMER_RELATIVE_MIG;
truncate table CUSTOMER_BELONG_MIG;
truncate table IND_INFO_MIG;
truncate table CUSTOMER_ADDRESS_MIG;
truncate table CUSTOMER_TEL_MIG;
truncate table CUSTOMER_CERT_MIG;
truncate table BUSINESS_APPROVE_MIG;
truncate table BUSINESS_CONTRACT_MIG;
truncate table BUSINESS_DUEBILL_MIG;
truncate table GUARANTY_CONTRACT_MIG;
truncate table GUARANTY_INFO_MIG;
truncate table GUARANTY_RELATIVE_MIG;
truncate table CL_INFO_MIG;
truncate table CL_DIVIDE_MIG;
truncate table CL_OCCUPY_MIG;
truncate table BUSINESS_WASTEBOOK_MIG;
truncate table GROUP_INFO_MIG;
truncate table GROUP_MEMBER_RELATIVE_MIG;
truncate table CONTRACT_RELATIVE_MIG;
truncate table CMS_INSURANCE_INFO_MIG;
truncate table CUSTOMER_INFO_MIG;
truncate table CL_CREDIT_SAME_MIG;
truncate table APPLY_BATCHRELATIVE_MIG;
truncate table CLASSIFY_RECORD_MIG;
truncate table MARGIN_INFO_MIG;
truncate table BUSINESS_IMAGE_RELATIVE_MIG;
truncate table BUSINESS_APPLY_MIG;
truncate table FLOW_OBJECT_MIG;
truncate table FLOW_TASK_MIG;
truncate table APPLY_RELATIVE_MIG;
truncate table APPROVE_RELATIVE_MIG;
truncate table BUSINESS_PUTOUT_MIG;
truncate table BILL_INFO_MIG;

--4.建立临时表主键
alter table ENT_INFO_MIG add constraint ENT_INFO_MIG_PK primary key (CUSTOMERID);
alter table CUSTOMER_RELATIVE_MIG add constraint CUSTOMER_RELATIVE_MIG_PK primary key (CUSTOMERID, RELATIVEID, RELATIONSHIP);
alter table CUSTOMER_BELONG_MIG add constraint CUSTOMER_BELONG_MIG_PK primary key (CUSTOMERID, ORGID, USERID);
alter table IND_INFO_MIG add constraint IND_INFO_MIG_PK primary key (CUSTOMERID);
alter table CUSTOMER_ADDRESS_MIG add constraint CUSTOMER_ADDRESS_MIG_PK primary key (SERIALNO);
alter table CUSTOMER_TEL_MIG add constraint CUSTOMER_TEL_MIG_PK primary key (SERIALNO);
alter table CUSTOMER_CERT_MIG add constraint CUSTOMER_CERT_MIG_PK primary key (SERIALNO);
alter table BUSINESS_APPROVE_MIG add constraint BUSINESS_APPROVE_MIG_PK primary key (SERIALNO);
alter table BUSINESS_CONTRACT_MIG add constraint BUSINESS_CONTRACT_MIG_PK primary key (SERIALNO);
alter table BUSINESS_DUEBILL_MIG add constraint BUSINESS_DUEBILL_MIG_PK primary key (SERIALNO);
alter table GUARANTY_CONTRACT_MIG add constraint GUARANTY_CONTRACT_MIG_PK primary key (SERIALNO);
alter table GUARANTY_INFO_MIG add constraint GUARANTY_INFO_MIG_PK primary key (GUARANTYID);
alter table GUARANTY_RELATIVE_MIG add constraint GUARANTY_RELATIVE_MIG_PK primary key (OBJECTTYPE, GUARANTYID, CONTRACTNO, OBJECTNO);
alter table CL_INFO_MIG add constraint CL_INFO_MIG_PK primary key (LINEID);
alter table CL_DIVIDE_MIG add constraint CL_DIVIDE_MIG_PK primary key (SERIALNO);
alter table CL_OCCUPY_MIG add constraint CL_OCCUPY_MIG_PK primary key (SERIALNO);
alter table BUSINESS_WASTEBOOK_MIG add constraint BUSINESS_WASTEBOOK_MIG_PK primary key (SERIALNO);
alter table GROUP_INFO_MIG add constraint GROUP_INFO_MIG_PK primary key (GROUPID);
alter table GROUP_MEMBER_RELATIVE_MIG add constraint GROUP_MEMBER_RELATIVE_MIG_PK primary key (SERIALNO);
alter table CONTRACT_RELATIVE_MIG add constraint CONTRACT_RELATIVE_MIG_PK unique (SERIALNO, OBJECTTYPE, OBJECTNO);
alter table CMS_INSURANCE_INFO_MIG add constraint CMS_INSURANCE_INFO_MIG_PK primary key (SERIALNO);
alter table CUSTOMER_INFO_MIG add constraint CUSTOMER_INFO_MIG_PK primary key (CUSTOMERID);
alter table CL_CREDIT_SAME_MIG add constraint CL_CREDIT_SAME_MIG_PK primary key (SERIALNO);
alter table APPLY_BATCHRELATIVE_MIG add constraint APPLY_BATCHRELATIVE_MIG_PK primary key (SERIALNO, OBJECTTYPE, RELATIVEBATCHSERIALNO);
alter table CLASSIFY_RECORD_MIG add constraint CLASSIFY_RECORD_MIG_PK primary key (SERIALNO, OBJECTTYPE, OBJECTNO);
alter table MARGIN_INFO_MIG add constraint MARGIN_INFO_MIG_PK primary key (SERIALNO);
alter table BUSINESS_IMAGE_RELATIVE_MIG add constraint BUSINESS_IMAGE_RELATIVE_MIG_PK primary key (SERIALNO);
alter table BUSINESS_APPLY_MIG add constraint BUSINESS_APPLY_MIG_PK primary key (SERIALNO);
alter table FLOW_OBJECT_MIG add constraint FLOW_OBJECT_MIG_PK primary key (OBJECTNO, OBJECTTYPE);
alter table FLOW_TASK_MIG add constraint FLOW_TASK_MIG_PK primary key (SERIALNO);
alter table APPLY_RELATIVE_MIG add constraint APPLY_RELATIVE_MIG_PK primary key (SERIALNO, OBJECTTYPE, OBJECTNO);
alter table APPROVE_RELATIVE_MIG add constraint APPROVE_RELATIVE_MIG_PK primary key (SERIALNO, OBJECTTYPE, OBJECTNO);
alter table BUSINESS_PUTOUT_MIG add constraint BUSINESS_PUTOUT_MIG_PK primary key (SERIALNO);