--1.担保合同-暂存标识默认登记完-1
update Guaranty_Contract_Mig set TempSaveFlag='1' where 1=1;
--2.个人信息表暂存标志
update ind_info_mig set tempsaveflag='1' where 1=1;

INSERT INTO APPROVE_RELATIVE_MIG(SERIALNO,OBJECTTYPE,OBJECTNO,RELATIVESUM)
SELECT DISTINCT BCM.RELATIVESERIALNO,'GuarantyContract',CRM.OBJECTNO,CRM.RELATIVESUM FROM BUSINESS_CONTRACT_MIG BCM 
              INNER JOIN CONTRACT_RELATIVE_MIG CRM ON BCM.SERIALNO=CRM.SERIALNO AND OBJECTTYPE='GuarantyContract';
              
INSERT INTO APPLY_RELATIVE_MIG(SERIALNO,OBJECTTYPE,OBJECTNO,RELATIVESUM)
SELECT * FROM APPROVE_RELATIVE_MIG;

commit;